// dns-tool:scrutiny design
package handlers

import (
        "fmt"
        "net/http"
        "strings"

        "dnstool/go-server/internal/analyzer"
        "dnstool/go-server/internal/dnsclient"

        "github.com/gin-gonic/gin"
)

const (
        iwBody      = `font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#0d1117;color:#c9d1d9;margin:0;padding:2rem`
        iwContainer = `max-width:800px;margin:0 auto`
        iwH1        = `font-size:1.4rem;margin-bottom:.5rem`
        iwMeta      = `color:#8b949e;font-size:.85rem;margin-bottom:1.5rem`
        iwMetaLink  = `color:#58a6ff;text-decoration:none`
        iwCard      = `background:#161b22;border:1px solid #30363d;border-radius:8px;padding:1.5rem;margin-bottom:1.5rem`
        iwCardH2    = `font-size:1.1rem;margin:0 0 .75rem 0`
        iwCardP     = `color:#8b949e;font-size:.9rem;margin:0 0 1rem 0;line-height:1.5`
        iwDlBtn     = `display:inline-block;background:#238636;color:#fff;padding:.5rem 1rem;border-radius:6px;text-decoration:none;font-size:.9rem;font-weight:500`
        iwSecBtn = `display:inline-block;background:#21262d;color:#c9d1d9;border:1px solid #30363d;padding:.5rem 1rem;border-radius:6px;text-decoration:none;font-size:.9rem;margin-left:.5rem`
)

const agentWrapperStyle = `
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 2rem; }
    .container { max-width: 800px; margin: 0 auto; }
    h1 { font-size: 1.4rem; margin-bottom: .5rem; }
    .meta { color: #8b949e; font-size: .85rem; margin-bottom: 1.5rem; }
    .meta a { color: #58a6ff; text-decoration: none; }
    .meta a:hover { text-decoration: underline; }
    .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
    .card h2 { font-size: 1.1rem; margin: 0 0 .75rem 0; }
    .card p { color: #8b949e; font-size: .9rem; margin: 0 0 1rem 0; line-height: 1.5; }
    .download-btn { display: inline-block; background: #238636; color: #fff; padding: .5rem 1rem; border-radius: 6px; text-decoration: none; font-size: .9rem; font-weight: 500; }
    .download-btn:hover { background: #2ea043; }
    .secondary-btn { display: inline-block; background: #21262d; color: #c9d1d9; border: 1px solid #30363d; padding: .5rem 1rem; border-radius: 6px; text-decoration: none; font-size: .9rem; margin-left: .5rem; }
    .secondary-btn:hover { border-color: #8b949e; }
    .preview { background: #0d1117; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; margin-top: 1rem; font-family: "SF Mono", "Fira Code", monospace; font-size: .8rem; color: #8b949e; overflow-x: auto; white-space: pre-wrap; word-break: break-all; max-height: 200px; overflow-y: auto; }
    .links { margin-top: 1.5rem; font-size: .9rem; }
    .links a { color: #58a6ff; text-decoration: none; margin-right: 1.5rem; }
    .links a:hover { text-decoration: underline; }
`

func inlineHead(title, desc, ogTitle, ogDesc string) string {
        return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>` + title + `</title>
  <meta name="description" content="` + desc + `">
  <meta name="robots" content="noindex">
  <meta property="og:title" content="` + ogTitle + `">
  <meta property="og:description" content="` + ogDesc + `">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="DNS Tool">
  <style>` + agentWrapperStyle + `</style>
</head>
<body style="` + iwBody + `">
  <div style="` + iwContainer + `">`
}

func inlineMeta(base string) string {
        return `
    <p style="` + iwMeta + `">Generated by <a href="` + esc(base) + `" style="` + iwMetaLink + `">DNS Tool</a></p>`
}

func (h *AgentHandler) SnapshotView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        snapshotURL := esc(fmt.Sprintf("%s/snapshot/%s", base, domain))
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "Observed Records Snapshot — "+ed,
                "Reconstructed DNS zone file for "+ed+" — observed records snapshot with SHA-3-512 integrity verification. Generated by DNS Tool.",
                "Observed Records Snapshot — "+ed,
                "Reconstructed DNS zone file for "+ed+" with SHA-3-512 integrity verification.",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">Observed Records Snapshot — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Reconstructed Zone File</h2>
      <p style="` + iwCardP + `">A reconstructed DNS zone file for <strong>` + ed + `</strong> built from observed public DNS records. This is not an authoritative zone transfer — it reflects what DNS Tool's resolvers observed at query time. All records are verified with SHA-3-512 integrity hashing.</p>
      <p style="` + iwCardP + `">Records include: A, AAAA, MX, NS, TXT (SPF, DKIM, DMARC, etc.), CNAME, CAA, TLSA, SRV, and discovered subdomains from Certificate Transparency logs.</p>
      <a href="` + snapshotURL + `" style="` + iwDlBtn + `">View Zone Snapshot</a>
      <a href="` + reportURL + `" style="` + iwSecBtn + `">Full Analysis Report</a>
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) JSONView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        apiURL := esc(fmt.Sprintf("%s/agent/api?q=%s", base, domain))
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "Full Intelligence Data (JSON) — "+ed,
                "Complete DNS security intelligence payload for "+ed+" in JSON format. Contains all collected data from RFC-grounded analysis including email authentication, transport security, subdomain discovery, and posture scoring.",
                "Full Intelligence Data — "+ed,
                "Complete DNS security intelligence payload for "+ed+" in structured JSON format.",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">Full Intelligence Data — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">JSON Intelligence Payload</h2>
      <p style="` + iwCardP + `">The complete DNS security intelligence dataset for <strong>` + ed + `</strong> in structured JSON format. This payload contains every data point collected during analysis:</p>
      <p style="` + iwCardP + `">Email authentication (SPF, DKIM, DMARC, BIMI), transport security (DNSSEC, MTA-STS, DANE, TLS-RPT, CAA), subdomain discovery via Certificate Transparency, registrar and WHOIS intelligence, posture scoring with Bayesian confidence intervals, and RFC citation provenance.</p>
      <a href="` + apiURL + `" style="` + iwDlBtn + `">View JSON Data</a>
      <a href="` + reportURL + `" style="` + iwSecBtn + `">Full Analysis Report</a>
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) CSVView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        csvURL := esc(fmt.Sprintf("%s/export/subdomains?domain=%s&format=csv", base, domain))

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "Discovered Subdomains — "+ed,
                "Subdomain reconnaissance data for "+ed+" in CSV format. Domains discovered via Certificate Transparency log analysis with provider, certificate, and CNAME metadata.",
                "Discovered Subdomains — "+ed,
                "Subdomain reconnaissance data for "+ed+" in CSV format from Certificate Transparency analysis.",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">Discovered Subdomains — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Subdomain Reconnaissance Data (CSV)</h2>
      <p style="` + iwCardP + `">Human-readable subdomain discovery data for <strong>` + ed + `</strong> exported in CSV format. Each row represents a discovered subdomain with associated metadata:</p>
      <p style="` + iwCardP + `">Fields include: subdomain name, discovery status, source (Certificate Transparency), CNAME target, certificate provider, first-seen and last-seen timestamps, and autodisc indicators. Suitable for import into spreadsheets, SIEM platforms, or threat intelligence tools.</p>
      <div style="text-align:center">
        <a href="` + csvURL + `" style="` + iwDlBtn + `">Download CSV Export</a>
      </div>
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) ChecksumView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))
        confidenceURL := esc(fmt.Sprintf("%s/confidence", base))

        var checksumURL string
        if h.lookupStore != nil {
                if recent, err := h.lookupStore.GetRecentAnalysisByDomain(c.Request.Context(), domain); err == nil {
                        checksumURL = esc(fmt.Sprintf("%s/api/analysis/%d/checksum", base, recent.ID))
                }
        }
        if checksumURL == "" {
                checksumURL = reportURL
        }

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "SHA-3 Integrity Checksum — "+ed,
                "SHA-3-512 cryptographic integrity checksum for the DNS security analysis of "+ed+". Verify that analysis data has not been tampered with.",
                "SHA-3 Integrity Checksum — "+ed,
                "Cryptographic integrity verification for the DNS analysis of "+ed+".",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">SHA-3 Integrity Checksum — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Cryptographic Verification</h2>
      <p style="` + iwCardP + `">Every DNS Tool analysis is hashed with SHA-3-512 (Keccak) to produce a tamper-evident integrity checksum. This checksum covers the complete analysis payload — all DNS records, security verdicts, posture scores, and metadata — ensuring the report has not been modified after generation.</p>
      <p style="` + iwCardP + `">The checksum JSON includes the algorithm identifier, hex-encoded hash, filename, analysis provenance (analysis ID, engine version), and ICAE confidence metrics. Use it to verify report authenticity in forensic, compliance, or legal contexts.</p>
      <a href="` + checksumURL + `" style="` + iwDlBtn + `">View Checksum (JSON)</a>
      <a href="` + confidenceURL + `" style="` + iwSecBtn + `">Confidence &amp; Audit</a>
      <a href="` + reportURL + `" style="` + iwSecBtn + `">Full Analysis Report</a>
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) WaybackHTMLView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)

        var waybackURL string
        if h.lookupStore != nil {
                if recent, err := h.lookupStore.GetRecentAnalysisByDomain(c.Request.Context(), domain); err == nil {
                        if recent.WaybackUrl != nil && *recent.WaybackUrl != "" && strings.HasPrefix(*recent.WaybackUrl, "https://web.archive.org/") {
                                waybackURL = esc(*recent.WaybackUrl)
                        }
                }
        }

        waybackAction := `<p style="` + iwCardP + `">No archived snapshot is available yet for this domain. The Wayback Machine archive is created asynchronously after analysis completes.</p>`
        if waybackURL != "" {
                waybackAction = `<div style="text-align:center"><a href="` + waybackURL + `" style="` + iwDlBtn + `">View Archived Snapshot</a></div>`
        }

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "Wayback Archive — "+ed,
                "Permanent Internet Archive (Wayback Machine) record of the DNS security analysis for "+ed+". Provides an immutable third-party archive of the analysis at the time it was generated.",
                "Wayback Archive — "+ed,
                "Permanent Wayback Machine archive of the DNS security analysis for "+ed+".",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">Wayback Archive — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Wayback Machine Archive</h2>
      <p style="` + iwCardP + `">DNS Tool automatically submits every analysis to the Internet Archive's Wayback Machine, creating a permanent, immutable, third-party record. This archived snapshot preserves the complete analysis as it appeared at the time of generation — providing independent verification for compliance, audit, and forensic purposes.</p>
      ` + waybackAction + `
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func validateAgentDomain(domain string) bool {
        return dnsclient.ValidateDomain(domain) || analyzer.IsWeb3Input(domain)
}
