// dns-tool:scrutiny design
package handlers

import (
        "fmt"
        "net/http"
        "strings"

        "dnstool/go-server/internal/analyzer"
        "dnstool/go-server/internal/dnsclient"

        "github.com/gin-gonic/gin"
)

const agentWrapperStyle = `
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 2rem; }
    .container { max-width: 800px; margin: 0 auto; }
    h1 { font-size: 1.4rem; margin-bottom: .5rem; }
    .meta { color: #8b949e; font-size: .85rem; margin-bottom: 1.5rem; }
    .meta a { color: #58a6ff; text-decoration: none; }
    .meta a:hover { text-decoration: underline; }
    .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
    .card h2 { font-size: 1.1rem; margin: 0 0 .75rem 0; }
    .card p { color: #8b949e; font-size: .9rem; margin: 0 0 1rem 0; line-height: 1.5; }
    .download-btn { display: inline-block; background: #238636; color: #fff; padding: .5rem 1rem; border-radius: 6px; text-decoration: none; font-size: .9rem; font-weight: 500; }
    .download-btn:hover { background: #2ea043; }
    .secondary-btn { display: inline-block; background: #21262d; color: #c9d1d9; border: 1px solid #30363d; padding: .5rem 1rem; border-radius: 6px; text-decoration: none; font-size: .9rem; margin-left: .5rem; }
    .secondary-btn:hover { border-color: #8b949e; }
    .preview { background: #0d1117; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; margin-top: 1rem; font-family: "SF Mono", "Fira Code", monospace; font-size: .8rem; color: #8b949e; overflow-x: auto; white-space: pre-wrap; word-break: break-all; max-height: 200px; overflow-y: auto; }
    .links { margin-top: 1.5rem; font-size: .9rem; }
    .links a { color: #58a6ff; text-decoration: none; margin-right: 1.5rem; }
    .links a:hover { text-decoration: underline; }
`

func (h *AgentHandler) SnapshotView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        snapshotURL := esc(fmt.Sprintf("%s/snapshot/%s", base, domain))
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var sb strings.Builder
        sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Observed Records Snapshot — ` + ed + `</title>
  <meta name="description" content="Reconstructed DNS zone file for ` + ed + ` — observed records snapshot with SHA-3-512 integrity verification. Generated by DNS Tool.">
  <meta name="robots" content="noindex">
  <meta property="og:title" content="Observed Records Snapshot — ` + ed + `">
  <meta property="og:description" content="Reconstructed DNS zone file for ` + ed + ` with SHA-3-512 integrity verification.">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="DNS Tool">
  <style>` + agentWrapperStyle + `</style>
</head>
<body>
  <div class="container">
    <h1>Observed Records Snapshot — ` + ed + `</h1>
    <p class="meta">Generated by <a href="` + esc(base) + `">DNS Tool</a> · <a href="` + reportURL + `">View full report →</a></p>
    <div class="card">
      <h2>Reconstructed Zone File</h2>
      <p>A reconstructed DNS zone file for <strong>` + ed + `</strong> built from observed public DNS records. This is not an authoritative zone transfer — it reflects what DNS Tool's resolvers observed at query time. All records are verified with SHA-3-512 integrity hashing.</p>
      <p>Records include: A, AAAA, MX, NS, TXT (SPF, DKIM, DMARC, etc.), CNAME, CAA, TLSA, SRV, and discovered subdomains from Certificate Transparency logs.</p>
      <a href="` + snapshotURL + `" class="download-btn">View Zone Snapshot</a>
      <a href="` + reportURL + `" class="secondary-btn">Full Analysis Report</a>
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) JSONView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        apiURL := esc(fmt.Sprintf("%s/agent/api?q=%s", base, domain))
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var sb strings.Builder
        sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Full Intelligence Data (JSON) — ` + ed + `</title>
  <meta name="description" content="Complete DNS security intelligence payload for ` + ed + ` in JSON format. Contains all collected data from RFC-grounded analysis including email authentication, transport security, subdomain discovery, and posture scoring.">
  <meta name="robots" content="noindex">
  <meta property="og:title" content="Full Intelligence Data — ` + ed + `">
  <meta property="og:description" content="Complete DNS security intelligence payload for ` + ed + ` in structured JSON format.">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="DNS Tool">
  <style>` + agentWrapperStyle + `</style>
</head>
<body>
  <div class="container">
    <h1>Full Intelligence Data — ` + ed + `</h1>
    <p class="meta">Generated by <a href="` + esc(base) + `">DNS Tool</a> · <a href="` + reportURL + `">View full report →</a></p>
    <div class="card">
      <h2>JSON Intelligence Payload</h2>
      <p>The complete DNS security intelligence dataset for <strong>` + ed + `</strong> in structured JSON format. This payload contains every data point collected during analysis:</p>
      <p>Email authentication (SPF, DKIM, DMARC, BIMI), transport security (DNSSEC, MTA-STS, DANE, TLS-RPT, CAA), subdomain discovery via Certificate Transparency, registrar and WHOIS intelligence, posture scoring with Bayesian confidence intervals, and RFC citation provenance.</p>
      <a href="` + apiURL + `" class="download-btn">View JSON Data</a>
      <a href="` + reportURL + `" class="secondary-btn">Full Analysis Report</a>
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) CSVView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        csvURL := esc(fmt.Sprintf("%s/export/subdomains?domain=%s&format=csv", base, domain))
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var sb strings.Builder
        sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Discovered Subdomains — ` + ed + `</title>
  <meta name="description" content="Subdomain reconnaissance data for ` + ed + ` in CSV format. Domains discovered via Certificate Transparency log analysis with provider, certificate, and CNAME metadata.">
  <meta name="robots" content="noindex">
  <meta property="og:title" content="Discovered Subdomains — ` + ed + `">
  <meta property="og:description" content="Subdomain reconnaissance data for ` + ed + ` in CSV format from Certificate Transparency analysis.">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="DNS Tool">
  <style>` + agentWrapperStyle + `</style>
</head>
<body>
  <div class="container">
    <h1>Discovered Subdomains — ` + ed + `</h1>
    <p class="meta">Generated by <a href="` + esc(base) + `">DNS Tool</a> · <a href="` + reportURL + `">View full report →</a></p>
    <div class="card">
      <h2>Subdomain Reconnaissance Data (CSV)</h2>
      <p>Human-readable subdomain discovery data for <strong>` + ed + `</strong> exported in CSV format. Each row represents a discovered subdomain with associated metadata:</p>
      <p>Fields include: subdomain name, discovery status, source (Certificate Transparency), CNAME target, certificate provider, first-seen and last-seen timestamps, and autodisc indicators. Suitable for import into spreadsheets, SIEM platforms, or threat intelligence tools.</p>
      <a href="` + csvURL + `" class="download-btn">Download CSV Export</a>
      <a href="` + reportURL + `" class="secondary-btn">Full Analysis Report</a>
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) ChecksumView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))
        confidenceURL := esc(fmt.Sprintf("%s/confidence", base))

        var checksumURL string
        if h.lookupStore != nil {
                if recent, err := h.lookupStore.GetRecentAnalysisByDomain(c.Request.Context(), domain); err == nil {
                        checksumURL = esc(fmt.Sprintf("%s/api/analysis/%d/checksum", base, recent.ID))
                }
        }
        if checksumURL == "" {
                checksumURL = reportURL
        }

        var sb strings.Builder
        sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>SHA-3 Integrity Checksum — ` + ed + `</title>
  <meta name="description" content="SHA-3-512 cryptographic integrity checksum for the DNS security analysis of ` + ed + `. Verify that analysis data has not been tampered with.">
  <meta name="robots" content="noindex">
  <meta property="og:title" content="SHA-3 Integrity Checksum — ` + ed + `">
  <meta property="og:description" content="Cryptographic integrity verification for the DNS analysis of ` + ed + `.">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="DNS Tool">
  <style>` + agentWrapperStyle + `</style>
</head>
<body>
  <div class="container">
    <h1>SHA-3 Integrity Checksum — ` + ed + `</h1>
    <p class="meta">Generated by <a href="` + esc(base) + `">DNS Tool</a> · <a href="` + reportURL + `">View full report →</a></p>
    <div class="card">
      <h2>Cryptographic Verification</h2>
      <p>Every DNS Tool analysis is hashed with SHA-3-512 (Keccak) to produce a tamper-evident integrity checksum. This checksum covers the complete analysis payload — all DNS records, security verdicts, posture scores, and metadata — ensuring the report has not been modified after generation.</p>
      <p>The checksum JSON includes the algorithm identifier, hex-encoded hash, filename, analysis provenance (analysis ID, engine version), and ICAE confidence metrics. Use it to verify report authenticity in forensic, compliance, or legal contexts.</p>
      <a href="` + checksumURL + `" class="download-btn">View Checksum (JSON)</a>
      <a href="` + confidenceURL + `" class="secondary-btn">Confidence &amp; Audit</a>
      <a href="` + reportURL + `" class="secondary-btn">Full Analysis Report</a>
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) WaybackHTMLView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var waybackURL string
        if h.lookupStore != nil {
                if recent, err := h.lookupStore.GetRecentAnalysisByDomain(c.Request.Context(), domain); err == nil {
                        if recent.WaybackUrl != nil && *recent.WaybackUrl != "" && strings.HasPrefix(*recent.WaybackUrl, "https://web.archive.org/") {
                                waybackURL = esc(*recent.WaybackUrl)
                        }
                }
        }

        waybackAction := `<p class="meta">No archived snapshot is available yet for this domain. The Wayback Machine archive is created asynchronously after analysis completes.</p>`
        if waybackURL != "" {
                waybackAction = `<a href="` + waybackURL + `" class="download-btn">View Archived Snapshot</a>`
        }

        var sb strings.Builder
        sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Wayback Archive — ` + ed + `</title>
  <meta name="description" content="Permanent Internet Archive (Wayback Machine) record of the DNS security analysis for ` + ed + `. Provides an immutable third-party archive of the analysis at the time it was generated.">
  <meta name="robots" content="noindex">
  <meta property="og:title" content="Wayback Archive — ` + ed + `">
  <meta property="og:description" content="Permanent Wayback Machine archive of the DNS security analysis for ` + ed + `.">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="DNS Tool">
  <style>` + agentWrapperStyle + `</style>
</head>
<body>
  <div class="container">
    <h1>Wayback Archive — ` + ed + `</h1>
    <p class="meta">Generated by <a href="` + esc(base) + `">DNS Tool</a> · <a href="` + reportURL + `">View full report →</a></p>
    <div class="card">
      <h2>Wayback Machine Archive</h2>
      <p>DNS Tool automatically submits every analysis to the Internet Archive's Wayback Machine, creating a permanent, immutable, third-party record. This archived snapshot preserves the complete analysis as it appeared at the time of generation — providing independent verification for compliance, audit, and forensic purposes.</p>
      ` + waybackAction + `
      <a href="` + reportURL + `" class="secondary-btn">Full Analysis Report</a>
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func validateAgentDomain(domain string) bool {
        return dnsclient.ValidateDomain(domain) || analyzer.IsWeb3Input(domain)
}
