// dns-tool:scrutiny design
package handlers

import (
        "fmt"
        "net/http"
        "strconv"
        "strings"

        "dnstool/go-server/internal/analyzer"
        "dnstool/go-server/internal/dnsclient"

        "github.com/gin-gonic/gin"
)

const (
        iwBody      = `font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#0d1117;color:#c9d1d9;margin:0;padding:2rem`
        iwContainer = `max-width:800px;margin:0 auto`
        iwH1        = `font-size:1.4rem;margin-bottom:.5rem`
        iwMeta      = `color:#8b949e;font-size:.85rem;margin-bottom:1.5rem`
        iwMetaLink  = `color:#58a6ff;text-decoration:none`
        iwCard      = `background:#161b22;border:1px solid #30363d;border-radius:8px;padding:1.5rem;margin-bottom:1.5rem`
        iwCardH2    = `font-size:1.1rem;margin:0 0 .75rem 0`
        iwCardP     = `color:#8b949e;font-size:.9rem;margin:0 0 1rem 0;line-height:1.5`
        iwDlBtn     = `display:inline-block;background:#238636;color:#fff;padding:.5rem 1rem;border-radius:6px;text-decoration:none;font-size:.9rem;font-weight:500`
        iwSecBtn = `display:inline-block;background:#21262d;color:#c9d1d9;border:1px solid #30363d;padding:.5rem 1rem;border-radius:6px;text-decoration:none;font-size:.9rem;margin-left:.5rem`
)

const agentWrapperStyle = `
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 2rem; }
    .container { max-width: 800px; margin: 0 auto; }
    h1 { font-size: 1.4rem; margin-bottom: .5rem; }
    .meta { color: #8b949e; font-size: .85rem; margin-bottom: 1.5rem; }
    .meta a { color: #58a6ff; text-decoration: none; }
    .meta a:hover { text-decoration: underline; }
    .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
    .card h2 { font-size: 1.1rem; margin: 0 0 .75rem 0; }
    .card p { color: #8b949e; font-size: .9rem; margin: 0 0 1rem 0; line-height: 1.5; }
    .download-btn { display: inline-block; background: #238636; color: #fff; padding: .5rem 1rem; border-radius: 6px; text-decoration: none; font-size: .9rem; font-weight: 500; }
    .download-btn:hover { background: #2ea043; }
    .secondary-btn { display: inline-block; background: #21262d; color: #c9d1d9; border: 1px solid #30363d; padding: .5rem 1rem; border-radius: 6px; text-decoration: none; font-size: .9rem; margin-left: .5rem; }
    .secondary-btn:hover { border-color: #8b949e; }
    .preview { background: #0d1117; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; margin-top: 1rem; font-family: "SF Mono", "Fira Code", monospace; font-size: .8rem; color: #8b949e; overflow-x: auto; white-space: pre-wrap; word-break: break-all; max-height: 200px; overflow-y: auto; }
    .links { margin-top: 1.5rem; font-size: .9rem; }
    .links a { color: #58a6ff; text-decoration: none; margin-right: 1.5rem; }
    .links a:hover { text-decoration: underline; }
`

func inlineHead(title, desc, ogTitle, ogDesc string) string {
        return inlineHeadExtra(title, desc, ogTitle, ogDesc, "")
}

func inlineHeadExtra(title, desc, ogTitle, ogDesc, extraHead string) string {
        return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>` + title + `</title>
  <meta name="description" content="` + desc + `">
  <meta name="robots" content="noindex">
  <meta property="og:title" content="` + ogTitle + `">
  <meta property="og:description" content="` + ogDesc + `">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="DNS Tool">` + extraHead + `
  <style>` + agentWrapperStyle + `</style>
</head>
<body style="` + iwBody + `">
  <div style="` + iwContainer + `">`
}

func inlineMeta(base string) string {
        return `
    <p style="` + iwMeta + `">Generated by <a href="` + esc(base) + `" style="` + iwMetaLink + `">DNS Tool</a></p>`
}

func domainContext(domain string) string {
        ed := esc(domain)
        return `
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">DNS Security Intelligence Context — ` + ed + `</h2>
      <p style="` + iwCardP + `">This artifact is part of the DNS security intelligence analysis for <strong>` + ed + `</strong>, produced by DNS Tool — IT Research in Motion. The analysis evaluates the complete DNS security posture of ` + ed + ` across SPF, DKIM, DMARC, BIMI, DNSSEC, DANE/TLSA, MTA-STS, TLS-RPT, and CAA. Posture scoring uses Bayesian confidence intervals aligned with ICD 203. All collected data is integrity-verified with SHA-3-512 checksums.</p>
    </div>`
}

func (h *AgentHandler) SnapshotView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        snapshotURL := esc(fmt.Sprintf("%s/snapshot/%s", base, domain))
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "Observed Records Snapshot — "+ed,
                "Reconstructed DNS zone file for "+ed+" — observed records snapshot with SHA-3-512 integrity verification. Generated by DNS Tool.",
                "Observed Records Snapshot — "+ed,
                "Reconstructed DNS zone file for "+ed+" with SHA-3-512 integrity verification.",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">Observed Records Snapshot — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Reconstructed Zone File</h2>
      <p style="` + iwCardP + `">A reconstructed DNS zone file for <strong>` + ed + `</strong> built from observed public DNS records. This is not an authoritative zone transfer — it reflects what DNS Tool's resolvers observed at query time. All records are verified with SHA-3-512 integrity hashing.</p>
      <p style="` + iwCardP + `">Records include: A, AAAA, MX, NS, TXT (SPF, DKIM, DMARC, etc.), CNAME, CAA, TLSA, SRV, and discovered subdomains from Certificate Transparency logs.</p>
      <a href="` + snapshotURL + `" style="` + iwDlBtn + `">View Zone Snapshot</a>
      <a href="` + reportURL + `" style="` + iwSecBtn + `">Full Analysis Report</a>
    </div>` + domainContext(domain) + `
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) JSONView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        apiURL := esc(fmt.Sprintf("%s/agent/api?q=%s", base, domain))
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "Full Intelligence Data (JSON) — "+ed,
                "Complete DNS security intelligence payload for "+ed+" in JSON format. Contains all collected data from RFC-grounded analysis including email authentication, transport security, subdomain discovery, and posture scoring.",
                "Full Intelligence Data — "+ed,
                "Complete DNS security intelligence payload for "+ed+" in structured JSON format.",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">Full Intelligence Data — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">JSON Intelligence Payload</h2>
      <p style="` + iwCardP + `">The complete DNS security intelligence dataset for <strong>` + ed + `</strong> in structured JSON format. This payload contains every data point collected during analysis:</p>
      <p style="` + iwCardP + `">Email authentication (SPF, DKIM, DMARC, BIMI), transport security (DNSSEC, MTA-STS, DANE, TLS-RPT, CAA), subdomain discovery via Certificate Transparency, registrar and WHOIS intelligence, posture scoring with Bayesian confidence intervals, and RFC citation provenance.</p>
      <a href="` + apiURL + `" style="` + iwDlBtn + `">View JSON Data</a>
      <a href="` + reportURL + `" style="` + iwSecBtn + `">Full Analysis Report</a>
    </div>` + domainContext(domain) + `
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) CSVView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        csvURL := esc(fmt.Sprintf("%s/export/subdomains?domain=%s&format=csv", base, domain))

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "Discovered Subdomains — "+ed,
                "Subdomain reconnaissance data for "+ed+" in CSV format. Domains discovered via Certificate Transparency log analysis with provider, certificate, and CNAME metadata.",
                "Discovered Subdomains — "+ed,
                "Subdomain reconnaissance data for "+ed+" in CSV format from Certificate Transparency analysis.",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">Discovered Subdomains — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Subdomain Reconnaissance Data (CSV)</h2>
      <p style="` + iwCardP + `">Human-readable subdomain discovery data for <strong>` + ed + `</strong> exported in CSV format. Each row represents a discovered subdomain with associated metadata:</p>
      <p style="` + iwCardP + `">Fields include: subdomain name, discovery status, source (Certificate Transparency), CNAME target, certificate provider, first-seen and last-seen timestamps, and autodisc indicators. Suitable for import into spreadsheets, SIEM platforms, or threat intelligence tools.</p>
      <div style="text-align:center">
        <a href="` + csvURL + `" style="` + iwDlBtn + `">Download CSV Export</a>
      </div>
    </div>` + domainContext(domain) + `
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) ChecksumView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))
        confidenceURL := esc(fmt.Sprintf("%s/confidence", base))

        var checksumURL string
        if h.lookupStore != nil {
                if recent, err := h.lookupStore.GetRecentAnalysisByDomain(c.Request.Context(), domain); err == nil {
                        checksumURL = esc(fmt.Sprintf("%s/api/analysis/%d/checksum", base, recent.ID))
                }
        }
        if checksumURL == "" {
                checksumURL = reportURL
        }

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "SHA-3 Integrity Checksum — "+ed,
                "SHA-3-512 cryptographic integrity checksum for the DNS security analysis of "+ed+". Verify that analysis data has not been tampered with.",
                "SHA-3 Integrity Checksum — "+ed,
                "Cryptographic integrity verification for the DNS analysis of "+ed+".",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">SHA-3 Integrity Checksum — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Cryptographic Verification</h2>
      <p style="` + iwCardP + `">Every DNS Tool analysis is hashed with SHA-3-512 (Keccak) to produce a tamper-evident integrity checksum. This checksum covers the complete analysis payload — all DNS records, security verdicts, posture scores, and metadata — ensuring the report has not been modified after generation.</p>
      <p style="` + iwCardP + `">The checksum JSON includes the algorithm identifier, hex-encoded hash, filename, analysis provenance (analysis ID, engine version), and ICAE confidence metrics. Use it to verify report authenticity in forensic, compliance, or legal contexts.</p>
      <a href="` + checksumURL + `" style="` + iwDlBtn + `">View Checksum (JSON)</a>
      <a href="` + confidenceURL + `" style="` + iwSecBtn + `">Confidence &amp; Audit</a>
      <a href="` + reportURL + `" style="` + iwSecBtn + `">Full Analysis Report</a>
    </div>` + domainContext(domain) + `
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

const waybackMaxRetries = 8

func (h *AgentHandler) WaybackHTMLView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)

        retryStr := c.DefaultQuery("retry", "0")
        retry, _ := strconv.Atoi(retryStr)
        if retry < 0 {
                retry = 0
        }

        var waybackURL string
        var hasRecentAnalysis bool
        if h.lookupStore != nil {
                if recent, err := h.lookupStore.GetRecentAnalysisByDomain(c.Request.Context(), domain); err == nil {
                        hasRecentAnalysis = true
                        if recent.WaybackUrl != nil && *recent.WaybackUrl != "" && strings.HasPrefix(*recent.WaybackUrl, "https://web.archive.org/") {
                                waybackURL = esc(*recent.WaybackUrl)
                        }
                }
        }

        var autoRefreshMeta string
        var waybackAction string

        if waybackURL != "" {
                waybackAction = `<div style="text-align:center"><a href="` + waybackURL + `" style="` + iwDlBtn + `">View Archived Snapshot</a></div>`
        } else if hasRecentAnalysis && retry < waybackMaxRetries {
                nextRetry := retry + 1
                refreshURL := esc(fmt.Sprintf("%s/agent/wayback-view?domain=%s&retry=%d", base, domain, nextRetry))
                autoRefreshMeta = `
  <meta http-equiv="refresh" content="15;url=` + refreshURL + `">`
                waybackAction = `<p style="` + iwCardP + `">The Wayback Machine archive is being created — this page will automatically check again in 15 seconds (attempt ` + strconv.Itoa(nextRetry) + `/` + strconv.Itoa(waybackMaxRetries) + `).</p>
      <div style="text-align:center;margin-top:1rem">
        <span style="display:inline-block;width:20px;height:20px;border:3px solid #30363d;border-top:3px solid #58a6ff;border-radius:50%;animation:spin 1s linear infinite"></span>
      </div>
      <style>@keyframes spin{to{transform:rotate(360deg)}}</style>`
        } else {
                manualURL := esc(fmt.Sprintf("%s/agent/wayback-view?domain=%s&retry=0", base, domain))
                reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))
                waybackAction = `<p style="` + iwCardP + `">The Wayback Machine archive is not yet available. The Internet Archive may still be processing the submission.</p>
      <div style="text-align:center;margin-top:1rem">
        <a href="` + manualURL + `" style="` + iwDlBtn + `">Check Again</a>
        <a href="` + reportURL + `" style="` + iwSecBtn + `">View Analysis Report</a>
      </div>`
        }

        var sb strings.Builder
        sb.WriteString(inlineHeadExtra(
                "Wayback Archive — "+ed,
                "Permanent Internet Archive (Wayback Machine) record of the DNS security analysis for "+ed+". Provides an immutable third-party archive of the analysis at the time it was generated.",
                "Wayback Archive — "+ed,
                "Permanent Wayback Machine archive of the DNS security analysis for "+ed+".",
                autoRefreshMeta,
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">Wayback Archive — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Wayback Machine Archive</h2>
      <p style="` + iwCardP + `">DNS Tool automatically submits every analysis to the Internet Archive's Wayback Machine, creating a permanent, immutable, third-party record. This archived snapshot preserves the complete analysis as it appeared at the time of generation — providing independent verification for compliance, audit, and forensic purposes.</p>
      ` + waybackAction + `
    </div>` + domainContext(domain) + `
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) TopologyView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        topoURL := esc(fmt.Sprintf("%s/topology?domain=%s", base, domain))
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "DNS Topology — "+ed,
                "Interactive DNS topology visualization for "+ed+" — protocol signal flow, resolver path mapping, and RFC source graph. Generated by DNS Tool.",
                "DNS Topology — "+ed,
                "DNS topology visualization and signal flow mapping for "+ed+".",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">DNS Topology — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Protocol Topology Visualization</h2>
      <p style="` + iwCardP + `">An interactive topology map of the DNS security infrastructure for <strong>` + ed + `</strong>. The visualization shows how DNS queries for ` + ed + ` flow through resolvers, nameservers, and mail exchangers, and maps each protocol check (SPF, DKIM, DMARC, DNSSEC, DANE, MTA-STS, TLS-RPT, CAA) to its authoritative RFC source.</p>
      <p style="` + iwCardP + `">The topology for ` + ed + ` reveals the relationships between DNS records, the delegation chain from root to authoritative nameservers, mail routing topology, and the certificate authority authorization graph. Use this map to understand the full infrastructure footprint of ` + ed + `.</p>
      <div style="text-align:center">
        <a href="` + topoURL + `" style="` + iwDlBtn + `">View Interactive Topology</a>
        <a href="` + reportURL + `" style="` + iwSecBtn + `">Full Analysis Report</a>
      </div>
    </div>` + domainContext(domain) + `
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) SourcesView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        sourcesURL := esc(fmt.Sprintf("%s/sources", base))
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "Sources & Methodology — "+ed,
                "RFC citations, data sources, and scoring methodology used in the DNS security analysis of "+ed+". Generated by DNS Tool.",
                "Sources & Methodology — "+ed,
                "Intelligence sources and methodology for the DNS security analysis of "+ed+".",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">Sources &amp; Methodology — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Intelligence Sources</h2>
      <p style="` + iwCardP + `">The DNS security analysis of <strong>` + ed + `</strong> is grounded in authoritative RFC specifications and open-source intelligence. Every protocol check performed on ` + ed + ` traces back to a specific RFC: SPF (RFC 7208), DKIM (RFC 6376), DMARC (RFC 7489), DANE (RFC 6698), MTA-STS (RFC 8461), TLS-RPT (RFC 8460), DNSSEC (RFC 4033-4035), and CAA (RFC 8659).</p>
      <p style="` + iwCardP + `">Data for ` + ed + ` is collected from public DNS resolvers, Certificate Transparency logs, WHOIS/RDAP databases, and the Internet Archive. Posture scoring for ` + ed + ` uses Bayesian confidence intervals aligned with ICD 203 standards. All findings for ` + ed + ` are cross-referenced against current best practices from M3AAWG, NIST, and CISA guidelines.</p>
      <div style="text-align:center">
        <a href="` + sourcesURL + `" style="` + iwDlBtn + `">View Full Sources</a>
        <a href="` + reportURL + `" style="` + iwSecBtn + `">Full Analysis Report</a>
      </div>
    </div>` + domainContext(domain) + `
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) ConfidenceView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)
        confURL := esc(fmt.Sprintf("%s/confidence", base))
        reportURL := esc(fmt.Sprintf(agentFmtAnalyze, base, domain))

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "Confidence & Integrity Audit — "+ed,
                "SHA-3 hash audit, integrity timestamps, and analysis confidence metrics for the DNS security analysis of "+ed+". Generated by DNS Tool.",
                "Confidence & Integrity Audit — "+ed,
                "Confidence metrics and integrity verification for the DNS analysis of "+ed+".",
        ))
        sb.WriteString(`
    <h1 style="` + iwH1 + `">Confidence &amp; Integrity Audit — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Analysis Confidence Metrics</h2>
      <p style="` + iwCardP + `">DNS Tool assigns confidence levels to every verdict in the analysis of <strong>` + ed + `</strong> using Bayesian scoring aligned with ICD 203 (Intelligence Community Directive 203). Each protocol assessment for ` + ed + ` — SPF, DKIM, DMARC, DNSSEC, DANE, MTA-STS, TLS-RPT, CAA — carries an individual confidence rating based on data quality, resolver agreement, and temporal consistency.</p>
      <p style="` + iwCardP + `">The integrity of all analysis data for ` + ed + ` is verified using SHA-3-512 (Keccak) cryptographic checksums. Timestamps record when each data point for ` + ed + ` was collected, and the complete analysis is archived to the Internet Archive Wayback Machine and registered with a Zenodo DOI for permanent provenance.</p>
      <div style="text-align:center">
        <a href="` + confURL + `" style="` + iwDlBtn + `">View Confidence Levels</a>
        <a href="` + reportURL + `" style="` + iwSecBtn + `">Full Analysis Report</a>
      </div>
    </div>` + domainContext(domain) + `
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func (h *AgentHandler) GuideView(c *gin.Context) {
        domain := extractAgentQuery(c)
        if domain == "" {
                c.String(http.StatusBadRequest, agentErrMissingDomain)
                return
        }
        if !validateAgentDomain(domain) {
                c.String(http.StatusBadRequest, agentErrInvalidDomain)
                return
        }

        base := h.Config.BaseURL
        ed := esc(domain)

        var sb strings.Builder
        sb.WriteString(inlineHead(
                "DNS Intelligence Guide — "+ed,
                "Orientation guide for the DNS security intelligence analysis of "+ed+". Produced by DNS Tool — IT Research in Motion.",
                "DNS Intelligence Guide — "+ed,
                "What this analysis contains and how to use it.",
        ))
        owlURL := esc(base + "/static/exports/owl-semaphore/derived/NORM-composite-dark-w160.png")

        sb.WriteString(`
    <div style="text-align:center;margin-bottom:1.5rem">
      <img src="` + owlURL + `" alt="DNS Tool — Owl Semaphore" width="160" height="160" style="border-radius:12px">
    </div>
    <h1 style="` + iwH1 + `;text-align:center">DNS Intelligence Guide — ` + ed + `</h1>`)
        sb.WriteString(inlineMeta(base))
        sb.WriteString(`
    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">What You're Looking At</h2>
      <p style="` + iwCardP + `">This is a complete DNS security intelligence analysis for <strong>` + ed + `</strong>, produced by <a href="` + esc(base) + `" style="` + iwMetaLink + `">DNS Tool</a> — a project of IT Help San Diego Inc.</p>
      <p style="` + iwCardP + `">The analysis covers every major DNS security protocol: SPF, DKIM, DMARC, BIMI, DNSSEC, DANE/TLSA, MTA-STS, TLS-RPT, and CAA. Each protocol check traces to an authoritative RFC. Posture scoring uses Bayesian confidence intervals aligned with ICD 203.</p>
    </div>

    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">What Each Section Does</h2>
      <p style="` + iwCardP + `"><strong>Engineer's Report</strong> — The primary analysis. Risk level, posture score, and detailed findings for every protocol.</p>
      <p style="` + iwCardP + `"><strong>Analysis History</strong> — Previous scans of this domain, if any. Useful for tracking security posture changes over time.</p>
      <p style="` + iwCardP + `"><strong>Security Badges</strong> — Visual posture indicators. The detailed badge shows the full breakdown; the covert badge is scotopic-optimized for dark environments.</p>
      <p style="` + iwCardP + `"><strong>Executive Brief</strong> — Board-ready summary. The covert report provides the same data in a low-visibility format.</p>
      <p style="` + iwCardP + `"><strong>Topology</strong> — Interactive visualization of DNS infrastructure: resolver paths, nameserver delegation, and mail routing.</p>
      <p style="` + iwCardP + `"><strong>Data Exports</strong> — Full JSON payload and CSV subdomain data for import into SIEM platforms, spreadsheets, or threat intelligence tools.</p>
      <p style="` + iwCardP + `"><strong>Integrity</strong> — SHA-3-512 checksums verify the analysis data has not been tampered with.</p>
      <p style="` + iwCardP + `"><strong>Remediation</strong> — Actionable steps to improve the domain's security posture based on the findings.</p>
      <p style="` + iwCardP + `"><strong>Wayback Archive</strong> — Permanent third-party record via the Internet Archive. Created asynchronously after analysis completes.</p>
      <p style="` + iwCardP + `"><strong>Sources &amp; Methodology</strong> — RFC citations, data sources, and the scoring methodology behind every verdict.</p>
    </div>

    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Freshness</h2>
      <p style="` + iwCardP + `">Every analysis delivers fresh data. DNS Tool queries live resolvers, Certificate Transparency logs, and WHOIS/RDAP databases in real time. Re-run a search after one hour to get a completely fresh scan.</p>
    </div>

    <div style="` + iwCard + `">
      <h2 style="` + iwCardH2 + `">Provenance</h2>
      <p style="` + iwCardP + `"><strong>Concept DOI:</strong> <a href="https://doi.org/10.5281/zenodo.19468134" style="` + iwMetaLink + `">10.5281/zenodo.19468134</a><br>
      <strong>License:</strong> BUSL-1.1<br>
      <strong>Publisher:</strong> IT Help San Diego Inc. — IT Research in Motion</p>
    </div>
  </div>
</body>
</html>`)

        c.Data(http.StatusOK, agentContentTypeHTML, []byte(sb.String()))
}

func validateAgentDomain(domain string) bool {
        return dnsclient.ValidateDomain(domain) || analyzer.IsWeb3Input(domain)
}
