{pkgs}: {
  deps = [
    pkgs.xcodebuild
    pkgs.python312Packages.nmapthon2
    pkgs.zlib
    pkgs.whois
    pkgs.unzip
    pkgs.trivy
    pkgs.tk
    pkgs.testssl
    pkgs.tcl
    pkgs.subfinder
    pkgs.sqlc
    pkgs.rsync
    pkgs.potrace
    pkgs.postgresql
    pkgs.pango
    pkgs.openssl
    pkgs.openjpeg
    pkgs.nuclei
    pkgs.nmap-formatter
    pkgs.nmap
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libsodium
    pkgs.librsvg
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.imagemagick
    pkgs.httpx
    pkgs.harfbuzz
    pkgs.glibcLocales
    pkgs.glib
    pkgs.gitleaks
    pkgs.ghostscript
    pkgs.freetype
    pkgs.fontconfig
    pkgs.dnsx
    pkgs.dnsutils
    pkgs.chromium
    pkgs.cacert
    pkgs.amass
  ];
}
