// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: confidence_scores.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConfidenceBackfillCandidates = `-- name: CountConfidenceBackfillCandidates :one
SELECT COUNT(*) FROM domain_analyses
WHERE analysis_success = TRUE
  AND full_results IS NOT NULL
`

func (q *Queries) CountConfidenceBackfillCandidates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countConfidenceBackfillCandidates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConfidenceScores = `-- name: CountConfidenceScores :one
SELECT COUNT(*) FROM confidence_scores
`

func (q *Queries) CountConfidenceScores(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countConfidenceScores)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertConfidenceScore = `-- name: InsertConfidenceScore :execrows

INSERT INTO confidence_scores (
    analysis_id, domain, protocol, score, resolver_count, resolver_agreement,
    evidence_factors, calibrated_score, raw_score, source, scanned_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (analysis_id, protocol) WHERE analysis_id IS NOT NULL DO NOTHING
`

type InsertConfidenceScoreParams struct {
	AnalysisID        *int32             `db:"analysis_id" json:"analysis_id"`
	Domain            string             `db:"domain" json:"domain"`
	Protocol          string             `db:"protocol" json:"protocol"`
	Score             pgtype.Numeric     `db:"score" json:"score"`
	ResolverCount     *int16             `db:"resolver_count" json:"resolver_count"`
	ResolverAgreement pgtype.Numeric     `db:"resolver_agreement" json:"resolver_agreement"`
	EvidenceFactors   []byte             `db:"evidence_factors" json:"evidence_factors"`
	CalibratedScore   pgtype.Numeric     `db:"calibrated_score" json:"calibrated_score"`
	RawScore          pgtype.Numeric     `db:"raw_score" json:"raw_score"`
	Source            string             `db:"source" json:"source"`
	ScannedAt         pgtype.Timestamptz `db:"scanned_at" json:"scanned_at"`
}

// Confidence scores: normalized per-scan, per-protocol confidence statistics.
// Written post-scan (source='scan') and by the admin backfill job (source='import').
// NOTE: rows include private/flagged scans — any PUBLIC consumer must join
// domain_analyses and filter private = FALSE AND scan_flag = FALSE.
func (q *Queries) InsertConfidenceScore(ctx context.Context, arg InsertConfidenceScoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertConfidenceScore,
		arg.AnalysisID,
		arg.Domain,
		arg.Protocol,
		arg.Score,
		arg.ResolverCount,
		arg.ResolverAgreement,
		arg.EvidenceFactors,
		arg.CalibratedScore,
		arg.RawScore,
		arg.Source,
		arg.ScannedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listConfidenceBackfillBatch = `-- name: ListConfidenceBackfillBatch :many
SELECT id, ascii_domain, full_results, created_at
FROM domain_analyses
WHERE id > $1
  AND analysis_success = TRUE
  AND full_results IS NOT NULL
ORDER BY id
LIMIT $2
`

type ListConfidenceBackfillBatchParams struct {
	ID    int32 `db:"id" json:"id"`
	Limit int32 `db:"limit" json:"limit"`
}

type ListConfidenceBackfillBatchRow struct {
	ID          int32            `db:"id" json:"id"`
	AsciiDomain string           `db:"ascii_domain" json:"ascii_domain"`
	FullResults []byte           `db:"full_results" json:"full_results"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
}

// NOTE: iterates ALL successful analyses (not just those missing confidence
// rows) — re-runs rely on InsertConfidenceScore's ON CONFLICT DO NOTHING for
// idempotency. An anti-join filter was skipped deliberately: full_results is
// json (not jsonb) and the table is scanned keyset-style once per admin run.
func (q *Queries) ListConfidenceBackfillBatch(ctx context.Context, arg ListConfidenceBackfillBatchParams) ([]ListConfidenceBackfillBatchRow, error) {
	rows, err := q.db.Query(ctx, listConfidenceBackfillBatch, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfidenceBackfillBatchRow{}
	for rows.Next() {
		var i ListConfidenceBackfillBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.AsciiDomain,
			&i.FullResults,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
