package icsae

import (
        "encoding/json"
        "os"
        "path/filepath"
        "sort"
        "strings"
        "testing"
)

// TestCatalogInSyncWithCanonical guards single-source-of-truth: the embedded copy
// must be byte-identical to the canonical catalog in dns-eval/. If this fails, the
// embedded copy has drifted — re-copy the canonical file.
func TestCatalogInSyncWithCanonical(t *testing.T) {
        canonical, err := os.ReadFile(filepath.Join("..", "..", "..", "dns-eval", "Mappings", "dns-to-controls.json"))
        if err != nil {
                t.Skipf("canonical catalog not reachable from this checkout: %v", err)
        }
        if string(canonical) != string(catalogJSON) {
                t.Fatalf("embedded dns-to-controls.json has drifted from canonical dns-eval/Mappings/dns-to-controls.json; re-copy the canonical file")
        }
}

// pyResult mirrors the summary emitted by dns-eval/Mappings/evaluate.py
// (tri-state, schema v9).
type pyResult struct {
        TotalControls    int      `json:"total_controls"`
        PassedCount      int      `json:"passed_count"`
        FailedCount      int      `json:"failed_count"`
        NACount          int      `json:"na_count"`
        NotMeasuredCount int      `json:"not_measured_count"`
        MeasuredControls int      `json:"measured_controls"`
        HighFailures     []string `json:"high_failures"`
        MediumFailures   []string `json:"medium_failures"`
        LowFailures      []string `json:"low_failures"`
        Passed           []string `json:"passed"`
        NotApplicable    []string `json:"not_applicable"`
        NotMeasured      []string `json:"not_measured"`
        Results          []struct {
                ID     string `json:"id"`
                Status string `json:"status"`
        } `json:"results"`
}

// TestCrossCheckPython proves the Go engine produces identical control verdicts to
// the canonical Python engine on the saved fixtures (testdata/*.input.json with
// testdata/*.expected.json generated by evaluate.py). Two engines, one catalog,
// must agree.
func TestCrossCheckPython(t *testing.T) {
        inputs, err := filepath.Glob(filepath.Join("testdata", "*.input.json"))
        if err != nil {
                t.Fatalf("glob testdata: %v", err)
        }
        if len(inputs) == 0 {
                t.Fatal("no testdata fixtures found")
        }

        for _, in := range inputs {
                base := strings.TrimSuffix(filepath.Base(in), ".input.json")
                t.Run(base, func(t *testing.T) {
                        rawIn, err := os.ReadFile(in)
                        if err != nil {
                                t.Fatalf("read input: %v", err)
                        }
                        var wrapper map[string]any
                        if err := json.Unmarshal(rawIn, &wrapper); err != nil {
                                t.Fatalf("parse input: %v", err)
                        }
                        fr, _ := wrapper["full_results"].(map[string]any)
                        if fr == nil {
                                t.Fatal("input missing full_results")
                        }

                        rawExp, err := os.ReadFile(filepath.Join("testdata", base+".expected.json"))
                        if err != nil {
                                t.Fatalf("read expected: %v", err)
                        }
                        var want pyResult
                        if err := json.Unmarshal(rawExp, &want); err != nil {
                                t.Fatalf("parse expected: %v", err)
                        }

                        got := Evaluate(fr)

                        if got.TotalControls != want.TotalControls ||
                                got.PassedCount != want.PassedCount ||
                                got.FailedCount != want.FailedCount ||
                                got.NACount != want.NACount ||
                                got.NotMeasuredCount != want.NotMeasuredCount ||
                                got.MeasuredControls != want.MeasuredControls {
                                t.Fatalf("count mismatch: got total=%d pass=%d fail=%d na=%d nm=%d measured=%d, want total=%d pass=%d fail=%d na=%d nm=%d measured=%d",
                                        got.TotalControls, got.PassedCount, got.FailedCount, got.NACount, got.NotMeasuredCount, got.MeasuredControls,
                                        want.TotalControls, want.PassedCount, want.FailedCount, want.NACount, want.NotMeasuredCount, want.MeasuredControls)
                        }

                        wantStatus := map[string]string{}
                        for _, r := range want.Results {
                                wantStatus[r.ID] = r.Status
                        }
                        for _, r := range got.Results {
                                if ws, ok := wantStatus[r.ID]; !ok {
                                        t.Errorf("control %s present in Go output but not Python", r.ID)
                                } else if ws != r.Status {
                                        t.Errorf("control %s: Go=%s Python=%s", r.ID, r.Status, ws)
                                }
                        }
                        if len(got.Results) != len(want.Results) {
                                t.Errorf("result count mismatch: Go=%d Python=%d", len(got.Results), len(want.Results))
                        }

                        assertSameSet(t, "high_failures", got.HighFailures, want.HighFailures)
                        assertSameSet(t, "medium_failures", got.MediumFailures, want.MediumFailures)
                        assertSameSet(t, "low_failures", got.LowFailures, want.LowFailures)
                        assertSameSet(t, "passed", got.Passed, want.Passed)
                        assertSameSet(t, "not_applicable", got.NotApplicable, want.NotApplicable)
                        assertSameSet(t, "not_measured", got.NotMeasured, want.NotMeasured)
                })
        }
}

func assertSameSet(t *testing.T, label string, got, want []string) {
        t.Helper()
        g := append([]string{}, got...)
        w := append([]string{}, want...)
        sort.Strings(g)
        sort.Strings(w)
        if strings.Join(g, ",") != strings.Join(w, ",") {
                t.Errorf("%s mismatch:\n  Go=%v\n  Python=%v", label, g, w)
        }
}

// TestHasNonEmptyListTypedSlices guards the Go-type vs JSON-type drift: live
// in-memory analyzer output uses concrete typed slices (e.g. []string), while
// JSON-round-tripped fixtures use []any. Both must be treated identically.
func TestHasNonEmptyListTypedSlices(t *testing.T) {
        cases := []struct {
                name string
                m    map[string]any
                want bool
        }{
                {"native []string non-empty", map[string]any{"records": []string{"a"}}, true},
                {"native []string empty", map[string]any{"records": []string{}}, false},
                {"json []any non-empty", map[string]any{"records": []any{"a"}}, true},
                {"json []any empty", map[string]any{"records": []any{}}, false},
                {"[]map[string]any non-empty", map[string]any{"records": []map[string]any{{"x": 1}}}, true},
                {"missing key", map[string]any{}, false},
                {"nil value", map[string]any{"records": nil}, false},
                {"wrong type (string)", map[string]any{"records": "abc"}, false},
        }
        for _, c := range cases {
                t.Run(c.name, func(t *testing.T) {
                        if got := hasNonEmptyList(c.m, "records"); got != c.want {
                                t.Errorf("hasNonEmptyList = %v, want %v", got, c.want)
                        }
                })
        }
}

// TestDeriveObservationsNativeCAA proves CAA_PRESENT is derived correctly when
// records arrives as a native []string (the live analyzer type), not just []any.
func TestDeriveObservationsNativeCAA(t *testing.T) {
        fr := map[string]any{
                "caa_analysis": map[string]any{
                        "status":  "success",
                        "records": []string{`0 issue "letsencrypt.org"`},
                },
        }
        obs := deriveObservations(fr)
        if v := obs["CAA_PRESENT"]; v == nil || !*v {
                t.Error("CAA_PRESENT != measured-true with native []string records; want true (live-type parity)")
        }
}

// TestEmptyScanGradesNothing pins the tri-state contract at its extreme: with
// nothing measured, the engine claims nothing. Every control is not_measured,
// the denominator is zero, and — the load-bearing half — NOTHING is failed.
// The pre-tri-state engine graded an empty scan as all-failed; this test makes
// that regression impossible to reintroduce silently.
func TestEmptyScanGradesNothing(t *testing.T) {
        res := Evaluate(map[string]any{})
        if res.FailedCount != 0 || res.PassedCount != 0 || res.NACount != 0 {
                t.Fatalf("empty scan graded controls: pass=%d fail=%d na=%d (want 0/0/0)",
                        res.PassedCount, res.FailedCount, res.NACount)
        }
        if res.MeasuredControls != 0 {
                t.Errorf("empty scan MeasuredControls=%d, want 0", res.MeasuredControls)
        }
        if res.NotMeasuredCount != res.TotalControls || res.TotalControls == 0 {
                t.Errorf("empty scan: not_measured=%d of total=%d, want all of a non-empty catalog",
                        res.NotMeasuredCount, res.TotalControls)
        }
}

// TestMeasuredAbsenceVsUnmeasured pins the distinction the tri-state port
// exists for, on the MTA-STS observation that carried the original defect:
// the producer's status "warning" means "No MTA-STS record found" — a MEASURED
// absence, graded false — while a missing section is NOT MEASURED, graded nil.
// The pre-tri-state engine mapped "warning" to true (absent graded present).
func TestMeasuredAbsenceVsUnmeasured(t *testing.T) {
        absent := deriveObservations(map[string]any{
                "mta_sts_analysis": map[string]any{"status": "warning"},
        })
        if v := absent["MTA_STS_DNS"]; v == nil || *v {
                t.Errorf("MTA-STS status=warning derived %v, want measured false (absence is measured, never present)", ptrState(v))
        }

        unmeasured := deriveObservations(map[string]any{})
        if v := unmeasured["MTA_STS_DNS"]; v != nil {
                t.Errorf("MTA-STS with no section derived %v, want nil (unmeasured is never a verdict)", ptrState(v))
        }
}

func ptrState(v *bool) string {
        if v == nil {
                return "nil"
        }
        if *v {
                return "true"
        }
        return "false"
}

// TestFailDirectionPair pins both directions of the tri-state fix on the
// control fed by the defect's original line (MAIL_POLICY_SIGNALING,
// requires_any: MTA_STS_DNS | TLS_RPT):
//
//  1. measured absence still FAILS and stays in the denominator — the fix is
//     tri-state grading, NOT a nullability change that swallows real findings;
//  2. unmeasured lands not_measured and leaves the denominator;
//  3. mixed measured-false + unmeasured is not_measured — requires_any cannot
//     claim all-measured-false, so no phantom failure.
func TestFailDirectionPair(t *testing.T) {
        statusOf := func(res Result, id string) string {
                for _, r := range res.Results {
                        if r.ID == id {
                                return r.Status
                        }
                }
                t.Fatalf("control %s not in results", id)
                return ""
        }

        measuredAbsent := Evaluate(map[string]any{
                "mta_sts_analysis": map[string]any{"status": "warning"},
                "tlsrpt_analysis":  map[string]any{"status": "warning"},
        })
        if st := statusOf(measuredAbsent, "MAIL_POLICY_SIGNALING"); st != "failed" {
                t.Fatalf("both channels measured absent: MAIL_POLICY_SIGNALING = %s, want failed (measured absence must still fail)", st)
        }
        if !contains(measuredAbsent.LowFailures, "MAIL_POLICY_SIGNALING") {
                t.Error("measured-absent MAIL_POLICY_SIGNALING missing from low_failures")
        }
        if contains(measuredAbsent.NotMeasured, "MAIL_POLICY_SIGNALING") {
                t.Error("measured-absent MAIL_POLICY_SIGNALING leaked into not_measured")
        }

        unmeasured := Evaluate(map[string]any{})
        if st := statusOf(unmeasured, "MAIL_POLICY_SIGNALING"); st != "not_measured" {
                t.Fatalf("nothing measured: MAIL_POLICY_SIGNALING = %s, want not_measured", st)
        }
        if contains(unmeasured.LowFailures, "MAIL_POLICY_SIGNALING") {
                t.Error("unmeasured MAIL_POLICY_SIGNALING graded a failure")
        }

        mixed := Evaluate(map[string]any{
                "mta_sts_analysis": map[string]any{"status": "warning"},
        })
        if st := statusOf(mixed, "MAIL_POLICY_SIGNALING"); st != "not_measured" {
                t.Fatalf("one channel measured false, one unmeasured: MAIL_POLICY_SIGNALING = %s, want not_measured (requires_any cannot claim all-measured-false)", st)
        }
}

// TestEvaluateNativeVsJSONParity is the strongest drift guard: a representative
// results map built with native Go types (typed slices, int counts, bools) must
// produce identical control verdicts to the same map after a JSON round-trip
// (which coerces []string->[]any and int->float64). If these diverge, the engine
// silently mis-scores live scans even while the JSON fixture cross-check passes.
func TestEvaluateNativeVsJSONParity(t *testing.T) {
        native := map[string]any{
                "spf_analysis":           map[string]any{"status": "success", "all_mechanism": "-all"},
                "dmarc_analysis":         map[string]any{"status": "success", "policy": "reject"},
                "dnssec_analysis":        map[string]any{"status": "success", "ad_flag": true, "chain_of_trust": "complete"},
                "caa_analysis":           map[string]any{"status": "success", "records": []string{`0 issue "le"`}},
                "dkim_analysis":          map[string]any{"status": "success", "primary_has_dkim": true},
                "dane_analysis":          map[string]any{"has_dane": true},
                "bimi_analysis":          map[string]any{"status": "success", "logo_valid": true},
                "mta_sts_analysis":       map[string]any{"status": "success"},
                "tlsrpt_analysis":        map[string]any{"status": "success"},
                "mail_posture":           map[string]any{"verdict": "mail"},
                "security_txt":           map[string]any{"found": true, "expired": false},
                "dangling_dns":           map[string]any{"status": "success", "dangling_count": 0},
                "delegation_consistency": map[string]any{"status": "success"},
                "secret_exposure":        map[string]any{"status": "clear", "finding_count": 0},
                "https_svcb":             map[string]any{"has_https": true},
                "cds_cdnskey":            map[string]any{"has_cds": true},
        }

        raw, err := json.Marshal(native)
        if err != nil {
                t.Fatalf("marshal: %v", err)
        }
        var jsonForm map[string]any
        if err := json.Unmarshal(raw, &jsonForm); err != nil {
                t.Fatalf("unmarshal: %v", err)
        }

        gNative := Evaluate(native)
        gJSON := Evaluate(jsonForm)

        if gNative.TotalControls != gJSON.TotalControls ||
                gNative.PassedCount != gJSON.PassedCount ||
                gNative.FailedCount != gJSON.FailedCount ||
                gNative.NACount != gJSON.NACount {
                t.Fatalf("count drift native vs json: native(t=%d p=%d f=%d na=%d) json(t=%d p=%d f=%d na=%d)",
                        gNative.TotalControls, gNative.PassedCount, gNative.FailedCount, gNative.NACount,
                        gJSON.TotalControls, gJSON.PassedCount, gJSON.FailedCount, gJSON.NACount)
        }

        nativeStatus := map[string]string{}
        for _, r := range gNative.Results {
                nativeStatus[r.ID] = r.Status
        }
        for _, r := range gJSON.Results {
                if ns, ok := nativeStatus[r.ID]; !ok {
                        t.Errorf("control %s in json output but not native", r.ID)
                } else if ns != r.Status {
                        t.Errorf("control %s drift: native=%s json=%s", r.ID, ns, r.Status)
                }
        }
        assertSameSet(t, "high_failures", gNative.HighFailures, gJSON.HighFailures)
        assertSameSet(t, "medium_failures", gNative.MediumFailures, gJSON.MediumFailures)
        assertSameSet(t, "low_failures", gNative.LowFailures, gJSON.LowFailures)
}

// TestWeaknessRefsVerifiedBridge guards the standards-to-vulnerability-taxonomy
// bridge: every CWE/CAPEC/VRT id referenced by a control must resolve in the
// weakness_registry (no orphan/fabricated ids), the flagship DMARC false-green-
// checkmark gap must carry its verified refs, and the coverage count must be
// surfaced honestly.
func TestWeaknessRefsVerifiedBridge(t *testing.T) {
        reg := Catalog().WeaknessRegistry
        if len(reg) == 0 {
                t.Fatal("weakness_registry is empty")
        }

        // No orphan references: every id used by any control resolves in the registry.
        for _, c := range Catalog().Mappings {
                if c.WeaknessRefs == nil {
                        continue
                }
                ids := append(append(append([]string{}, c.WeaknessRefs.CWE...), c.WeaknessRefs.CAPEC...), c.WeaknessRefs.VRT...)
                for _, id := range ids {
                        if _, ok := reg[id]; !ok {
                                t.Errorf("control %s references %q which is missing from weakness_registry", c.ID, id)
                        }
                }
                if c.WeaknessRefs.MappingConfidence == "" || c.WeaknessRefs.MappingRationale == "" {
                        t.Errorf("control %s has weakness_refs without confidence/rationale", c.ID)
                }
        }

        // Flagship: DMARC enforcement failure (p=none / p=quarantine) must surface
        // the verified spoofing weakness refs that prove "compliant != safe".
        res := Evaluate(map[string]any{
                "dmarc_analysis": map[string]any{"status": "success", "policy": "none"},
        })
        var dmarc *ControlResult
        for i := range res.Results {
                if res.Results[i].ID == "DMARC_ENFORCEMENT" {
                        dmarc = &res.Results[i]
                }
        }
        if dmarc == nil {
                t.Fatal("DMARC_ENFORCEMENT control not found in results")
        }
        if dmarc.Status != "failed" {
                t.Fatalf("DMARC_ENFORCEMENT expected failed at p=none, got %s", dmarc.Status)
        }
        if dmarc.WeaknessRefs == nil {
                t.Fatal("DMARC_ENFORCEMENT failure carries no weakness_refs")
        }
        if !contains(dmarc.WeaknessRefs.CWE, "CWE-290") {
                t.Errorf("DMARC_ENFORCEMENT missing CWE-290, got %v", dmarc.WeaknessRefs.CWE)
        }
        if !contains(dmarc.WeaknessRefs.VRT, "VRT:email_spoofing_to_inbox_due_to_missing_or_misconfigured_dmarc_on_email_domain") {
                t.Errorf("DMARC_ENFORCEMENT missing DMARC spoofing VRT ref, got %v", dmarc.WeaknessRefs.VRT)
        }

        // Coverage is surfaced and matches the controls that actually carry refs.
        var mapped int
        for _, c := range Catalog().Mappings {
                if c.WeaknessRefs != nil {
                        mapped++
                }
        }
        if res.MappedControls != mapped {
                t.Errorf("MappedControls=%d but %d controls carry weakness_refs", res.MappedControls, mapped)
        }
        if mapped == 0 {
                t.Fatal("no controls carry weakness_refs")
        }
}

func contains(s []string, v string) bool {
        for _, x := range s {
                if x == v {
                        return true
                }
        }
        return false
}

// TestWeaknessRegistryIntegrity hardens the zero-fabrication guarantee: every
// registry entry must resolve to its authoritative source, and the id prefix must
// match the publisher/URL (CWE-* -> MITRE CWE, CAPEC-* -> MITRE CAPEC, VRT:* ->
// Bugcrowd VRT). A mistyped or mis-sourced id fails the build.
func TestWeaknessRegistryIntegrity(t *testing.T) {
        for id, ref := range Catalog().WeaknessRegistry {
                if ref.Title == "" || ref.URL == "" || ref.Publisher == "" {
                        t.Errorf("%s: missing title/url/publisher", id)
                }
                switch {
                case strings.HasPrefix(id, "CWE-"):
                        if !strings.Contains(ref.URL, "cwe.mitre.org") || ref.Publisher != "MITRE CWE" {
                                t.Errorf("%s: expected MITRE CWE source, got %q / %q", id, ref.Publisher, ref.URL)
                        }
                case strings.HasPrefix(id, "CAPEC-"):
                        if !strings.Contains(ref.URL, "capec.mitre.org") || ref.Publisher != "MITRE CAPEC" {
                                t.Errorf("%s: expected MITRE CAPEC source, got %q / %q", id, ref.Publisher, ref.URL)
                        }
                case strings.HasPrefix(id, "VRT:"):
                        if !strings.Contains(ref.URL, "bugcrowd.com") {
                                t.Errorf("%s: expected Bugcrowd VRT source, got %q", id, ref.URL)
                        }
                default:
                        t.Errorf("%s: unrecognized id prefix (must be CWE-/CAPEC-/VRT:)", id)
                }
        }
}
