// dns-tool:scrutiny plumbing
package logging

const (
        CategoryScan       = "scan"
        CategorySecurity   = "security"
        CategoryPerformance = "performance"
        CategorySystem     = "system"
        CategoryExternalAPI = "external_api"

        EventScanStarted     = "scan_started"
        EventScanCompleted   = "scan_completed"
        EventScanFailed      = "scan_failed"
        EventPhaseStarted    = "phase_started"
        EventPhaseFinished   = "phase_finished"
        EventAuthFailure     = "auth_failure"
        EventCSRFReject      = "csrf_reject"
        EventRateLimitHit    = "rate_limit_hit"
        EventPanic           = "panic_recovered"
        EventSlowPhase       = "slow_phase"
        EventExternalCall    = "external_call"
        EventCacheHit        = "cache_hit"
        EventCacheMiss       = "cache_miss"
        EventStartup         = "startup"
        EventShutdown        = "shutdown"
        EventDBError         = "db_error"
        EventResolverFailure = "resolver_failure"

        AttrEvent          = "event"
        AttrCategory       = "category"
        AttrTraceID        = "trace_id"
        AttrAnalysisID     = "analysis_id"
        AttrScanToken      = "scan_token"
        AttrDomain         = "domain"
        AttrPhaseGroup     = "phase_group"
        AttrPhaseTask      = "phase_task"
        AttrElapsedMs      = "elapsed_ms"
        AttrOutcome        = "outcome"
        AttrErrorClass     = "error_class"
        AttrErrorChain     = "error_chain"
        AttrExternalService = "external_service"
        AttrHTTPStatus     = "http_status"
        AttrCacheHit       = "cache_hit"
        AttrRemoteAddr     = "remote_addr"
)
